### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by danichikawa26** [CarlosNZ/fig-tree-evaluator#113]
Using the lib, I realized that the error returned when I make an HTTP request is just the status code with a generic message. But when I see the consoles, I can see that the error returned from the service that the lib itself prints is the entire code with: statusCode, code, error and message.
Is it possible to return the entire error object?

**Example of returned error:**
```
Error: Operator: POST
Request failed with status code 400
```

**Desired returned error:**
```
{
code: "FST_ERR_VALIDATION"
error: "Bad request"
message: "body must have required property 'id'"
statusCode: 400
}
```

Thanks!

**Comment by CarlosNZ** [comment]
Thanks for the suggestion. Yes, I probably should make the original underlying error exposed. 

I have the `returnErrorAsString` option, and I wanted to make sure that the presented string was something simple and readable, hence why I've done it like this. But yeah, when throwing, it should just bubble the original error straight up. 

I'll get onto this.

**Comment by CarlosNZ** [comment]
Hi @danichikawa26, I've made a PR with these improvements: #114 

I'll merge this and push out a new release tomorrow sometime, so look out for that.

Have a read of the new "Error handling" section in the README for an overview of the Error structure: https://github.com/CarlosNZ/fig-tree-evaluator/blob/113-error-handling-improvement/README.md#error-handling

**Comment by danichikawa26** [comment]
Nice! Thanks, @CarlosNZ 
I also noticed that only GET and POST methods are allowed in HTTP requests. 
Is it possible to extend the Http Client and use, for example, PUT method?

**Comment by CarlosNZ** [comment]
> I also noticed that only GET and POST methods are allowed in HTTP requests.
> Is it possible to extend the Http Client and use, for example, PUT method?

Hmm, I'm a bit reluctant to add more HTTP methods, since I would have thought that GET and POST would cover almost all use cases. The other methods are primarily for modifying a resource, and this library is not really intended to perform state change/side effects on external resources, just for evaluating inputs. The primary purpose of the library is to expose arbitrary logic to a configuration file using JSON, not to allow data modification -- in fact it's kind of intended to *prevent* that.

Having said that, there's nothing stopping you extending it however you want by passing in additional "Custom functions": https://github.com/CarlosNZ/fig-tree-evaluator?tab=readme-ov-file#custom_functions
(You can even give them a "shortcut" name by defining a [fragment](https://github.com/CarlosNZ/fig-tree-evaluator?tab=readme-ov-file#fragments), so it could be syntactically very similar to the standard operators)

So I'd suggest using that for now, and I'll reconsider down the track if there's enough interest and I can see the possible use cases that seem appropriate to use this library for.

**Comment by CarlosNZ** [comment]
Closing, error improvements now in [v2.16.1](https://www.npmjs.com/package/fig-tree-evaluator/v/2.16.1) release.

Docs: https://github.com/CarlosNZ/fig-tree-evaluator?tab=readme-ov-file#error-handling
